---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: giddyos
# description will be included in the image's metadata
description: This is my personal OS image. Based on Silverblue

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: os-release
    properties:
      ID: giddyos
      ID_LIKE: silverblue
      NAME: GiddyOS
      PRETTY_NAME: GiddyOS

  - type: dnf
    repos:
      files:
        - terra.repo
    install:
      packages:
        - btop
        - cargo
        - docker-cli
        - docker-compose
        - gh
        - git
        - input-remapper
        - nextcloud-client
        - nextcloud-client-nautilus
        - topgrade
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: false # Send notification after install/uninstall is finished (true/false)
        scope: system
        # install: 
        #   - org.mozilla.firefox
        #   - org.mozilla.Thunderbird
        #   - com.mattjakeman.ExtensionManager
        #   - com.valvesoftware.Steam
        #   - com.visualstudio.code
        #   - ca.desrt.dconf-editor
        #   - com.github.tchx84.Flatseal
        #   - com.ranfdev.DistroShelf
        #   - com.usebottles.bottles
        #   - io.github.flattool.Ignition
        #   - io.github.pwr_solaar.solaar
        #   - it.mijorus.gearlever
        #   - net.codelogistics.webapps
        #   - org.gnome.Boxes
        #   - org.gnome.FileRoller
        #   - page.codeberg.libre_menu_editor.LibreMenuEditor
        #   - com.discordapp.Discord
        #   - com.heroicgameslauncher.hgl
        #   - com.spotify.Client
        #   - io.github.Faugus.faugus-launcher
        #   - io.github.kolunmi.Bazaar
        #   - net.lutris.Lutris
        #   - org.gnome.SimpleScan
        #   - org.gnome.TextEditor
        #   - org.libreoffice.LibreOffice
        #   - org.videolan.VLC
      - scope: user

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: justfiles
    validate: true
    install: true

  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry

  - type: gnome-extensions
    install:
      - AppIndicator and KStatusNotifierItem Support
      - Caffeine
      - Dash to Panel
      - Forge
      - App Grid Wizard

  - type: gschema-overrides

  # - type: chezmoi
  #   repository: "https://github.com/saltscratch/dotfiles" # my dotfiles repo
  #   file-conflict-policy: replace # override changed files with those from the repo

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # - type: yafti
  #   custom-flatpaks:
  #     - Firefox : org.mozilla.firefox
  #     - Thunderbird : org.mozilla.Thunderbird
